<?php

// цвета
// https://www.w3schools.com/cssref/css_colors.asp

$data = [
    'Aquamarine' => __( 'Aquamarine', 'zzz-translate' ),
    'aquamarine' => __( 'aquamarine', 'zzz-translate' ),
    'Azure'      => __( 'Azure', 'zzz-translate' ),
    'azure'      => __( 'azure', 'zzz-translate' ),
    'Beige'      => __( 'Beige', 'zzz-translate' ),
    'beige'      => __( 'beige', 'zzz-translate' ),
    'Black'      => __( 'Black', 'zzz-translate' ),
    'black'      => __( 'black', 'zzz-translate' ),
    'Blue'       => __( 'Blue', 'zzz-translate' ),
    'blue'       => __( 'blue', 'zzz-translate' ),
    'Brown'      => __( 'Brown', 'zzz-translate' ),
    'brown'      => __( 'brown', 'zzz-translate' ),
    'Crimson'    => __( 'Crimson', 'zzz-translate' ),
    'crimson'    => __( 'crimson', 'zzz-translate' ),
    'Cyan'       => __( 'Cyan', 'zzz-translate' ),
    'cyan'       => __( 'cyan', 'zzz-translate' ),
    'Fuchsia'    => __( 'Fuchsia', 'zzz-translate' ),
    'fuchsia'    => __( 'fuchsia', 'zzz-translate' ),
    'Gray'       => __( 'Gray', 'zzz-translate' ),
    'gray'       => __( 'gray', 'zzz-translate' ),
    'Grey'       => __( 'Grey', 'zzz-translate' ),
    'grey'       => __( 'grey', 'zzz-translate' ),
    'Green'      => __( 'Green', 'zzz-translate' ),
    'green'      => __( 'green', 'zzz-translate' ),
    'Khaki'      => __( 'Khaki', 'zzz-translate' ),
    'khaki'      => __( 'khaki', 'zzz-translate' ),
    'Magenta'    => __( 'Magenta', 'zzz-translate' ),
    'magenta'    => __( 'magenta', 'zzz-translate' ),
    'Maroon'     => __( 'Maroon', 'zzz-translate' ),
    'maroon'     => __( 'maroon', 'zzz-translate' ),
    'Orange'     => __( 'Orange', 'zzz-translate' ),
    'orange'     => __( 'orange', 'zzz-translate' ),
    'Pink'       => __( 'Pink', 'zzz-translate' ),
    'pink'       => __( 'pink', 'zzz-translate' ),
    'Purple'     => __( 'Purple', 'zzz-translate' ),
    'purple'     => __( 'purple', 'zzz-translate' ),
    'Red'        => __( 'Red', 'zzz-translate' ),
    'red'        => __( 'red', 'zzz-translate' ),
    'Turquoise'  => __( 'Turquoise', 'zzz-translate' ),
    'turquoise'  => __( 'turquoise', 'zzz-translate' ),
    'Violet'     => __( 'Violet', 'zzz-translate' ),
    'violet'     => __( 'violet', 'zzz-translate' ),
    'White'      => __( 'White', 'zzz-translate' ),
    'white'      => __( 'white', 'zzz-translate' ),
    'Yellow'     => __( 'Yellow', 'zzz-translate' ),
    'yellow'     => __( 'yellow', 'zzz-translate' ),
];
