<?php

// список валют

$data = [
    'AUD'      => __( 'Australian Dollar', 'zzz-translate' ),
    'Bitcoin'  => __( 'Bitcoin', 'zzz-translate' ),
    'bitcoin'  => __( 'bitcoin', 'zzz-translate' ),
    'BRL'      => __( 'Brazilian Real', 'zzz-translate' ),
    'GBP'      => __( 'British Pound', 'zzz-translate' ),
    'CAD'      => __( 'Canadian Dollar', 'zzz-translate' ),
    'CNY'      => __( 'Chinese Yen (¥)', 'zzz-translate' ),
    'CNY'      => __( 'Chinese Yuan (元)', 'zzz-translate' ),
    'CZK'      => __( 'Czech Koruna', 'zzz-translate' ),
    'Currency' => __( 'Currency', 'zzz-translate' ),
    'currency' => __( 'currency', 'zzz-translate' ),
    'DKK'      => __( 'Danish Krone', 'zzz-translate' ),
    'Dollar'   => __( 'Dollar', 'zzz-translate' ),
    'Dollar2'  => __( 'dollar', 'zzz-translate' ),
    'Ethereum' => __( 'Ethereum', 'zzz-translate' ),
    'ethereum' => __( 'ethereum', 'zzz-translate' ),
    'EUR'      => __( 'Euro', 'zzz-translate' ),
    'HKD'      => __( 'Hong Kong Dollar', 'zzz-translate' ),
    'HUF'      => __( 'Hungarian Forint', 'zzz-translate' ),
    'INR'      => __( 'Indian Rupee', 'zzz-translate' ),
    'IDR'      => __( 'Indonesian Rupiah', 'zzz-translate' ),
    'ILS'      => __( 'Israeli New Sheqel', 'zzz-translate' ),
    'JPY'      => __( 'Japanese Yen', 'zzz-translate' ),
    'KRW'      => __( 'Korean Won', 'zzz-translate' ),
    'Litecoin' => __( 'Litecoin', 'zzz-translate' ),
    'litecoin' => __( 'litecoin', 'zzz-translate' ),
    'MYR'      => __( 'Malaysian Ringgit', 'zzz-translate' ),
    'MXN'      => __( 'Mexican Peso', 'zzz-translate' ),
    'NGN'      => __( 'Nigerian Naira', 'zzz-translate' ),
    'NZD'      => __( 'New Zealand Dollar', 'zzz-translate' ),
    'NOK'      => __( 'Norwegian Krone', 'zzz-translate' ),
    'PHP'      => __( 'Philippine Peso', 'zzz-translate' ),
    'PLN'      => __( 'Polish Złoty', 'zzz-translate' ),
    'Rouble'   => __( 'Rouble', 'zzz-translate' ),
    'rouble'   => __( 'rouble', 'zzz-translate' ),
    'Ruble'    => __( 'Ruble', 'zzz-translate' ),
    'ruble'    => __( 'ruble', 'zzz-translate' ),
    'RUB'      => __( 'Russian Ruble', 'zzz-translate' ),
    'SEK'      => __( 'Swedish Krona', 'zzz-translate' ),
    'SGD'      => __( 'Singapore Dollar', 'zzz-translate' ),
    'ZAR'      => __( 'South African Rand', 'zzz-translate' ),
    'CHF'      => __( 'Swiss Franc', 'zzz-translate' ),
    'TWD'      => __( 'Taiwan New Dollar', 'zzz-translate' ),
    'THB'      => __( 'Thai Baht', 'zzz-translate' ),
    'TRL'      => __( 'Turkish Lira', 'zzz-translate' ),
    'USD'      => __( 'US Dollar', 'zzz-translate' ),
    'USDCENT'  => __( 'US Dollar Cent', 'zzz-translate' ),
    'VND'      => __( 'Vietnamese Dong', 'zzz-translate' ),
];
