<?php

// даты

$data = [
    'January'       => __( 'January', 'zzz-translate' ),
    'February'      => __( 'February', 'zzz-translate' ),
    'March'         => __( 'March', 'zzz-translate' ),
    'April'         => __( 'April', 'zzz-translate' ),
    'May'           => __( 'May', 'zzz-translate' ),
    'June'          => __( 'June', 'zzz-translate' ),
    'July'          => __( 'July', 'zzz-translate' ),
    'August'        => __( 'August', 'zzz-translate' ),
    'September'     => __( 'September', 'zzz-translate' ),
    'October'       => __( 'October', 'zzz-translate' ),
    'November'      => __( 'November', 'zzz-translate' ),
    'December'      => __( 'December', 'zzz-translate' ),
    'Monday'        => __( 'Monday', 'zzz-translate' ),
    'Tuesday'       => __( 'Tuesday', 'zzz-translate' ),
    'Wednesday'     => __( 'Wednesday', 'zzz-translate' ),
    'Thursday'      => __( 'Thursday', 'zzz-translate' ),
    'Friday'        => __( 'Friday', 'zzz-translate' ),
    'Saturday'      => __( 'Saturday', 'zzz-translate' ),
    'Sunday'        => __( 'Sunday', 'zzz-translate' ),
    'Mon'           => __( 'Mon', 'zzz-translate' ),
    'Tue'           => __( 'Tue', 'zzz-translate' ),
    'Wed'           => __( 'Wed', 'zzz-translate' ),
    'Thu'           => __( 'Thu', 'zzz-translate' ),
    'Fri'           => __( 'Fri', 'zzz-translate' ),
    'Sat'           => __( 'Sat', 'zzz-translate' ),
    'Sun'           => __( 'Sun', 'zzz-translate' ),
    'Day'           => __( 'Day', 'zzz-translate' ),
    'Week'          => __( 'Week', 'zzz-translate' ),
    'Month'         => __( 'Month', 'zzz-translate' ),
    'Year'          => __( 'Year', 'zzz-translate' ),
    'Time'          => __( 'Time', 'zzz-translate' ),
    'Hour'          => __( 'Hour', 'zzz-translate' ),
    'Minute'        => __( 'Minute', 'zzz-translate' ),
    'Second'        => __( 'Second', 'zzz-translate' ),
    'Millisecond'   => __( 'Millisecond', 'zzz-translate' ),
    'Microsecond'   => __( 'Microsecond', 'zzz-translate' ),
    'AM'            => __( 'AM', 'zzz-translate' ),
    'PM'            => __( 'PM', 'zzz-translate' ),
    '12 hour'       => __( '12 hour', 'zzz-translate' ),
    '24 hour'       => __( '24 hour', 'zzz-translate' ),
    'Date / Time'   => __( 'Date / Time', 'zzz-translate' ),
    'Last day'      => __( 'Last day', 'zzz-translate' ),
    'Last 7 days'   => __( 'Last 7 days', 'zzz-translate' ),
    'Last 30 days'  => __( 'Last 30 days', 'zzz-translate' ),
    'Last hour'     => __( 'Last hour', 'zzz-translate' ),
    'Last 12 hours' => __( 'Last 12 hours', 'zzz-translate' ),
    'Read Time'     => __( 'Read Time:', 'zzz-translate' ),
    'Time Format'   => __( 'Time Format', 'zzz-translate' ),
    'Time Zone'     => __( 'Time Zone', 'zzz-translate' ),
];
