<?php

// непереводимые термины

$data = [
    '.htaccess'      => __( '.htaccess', 'zzz-translate' ),
    '404'            => __( '404', 'zzz-translate' ),
    'BCC'            => __( 'BCC', 'zzz-translate' ),
    'CC'             => __( 'CC', 'zzz-translate' ),
    'cron'           => __( 'cron', 'zzz-translate' ),
    'CRON'           => __( 'CRON', 'zzz-translate' ),
    'css'            => __( 'css', 'zzz-translate' ),
    'CSS'            => __( 'CSS', 'zzz-translate' ),
    'Gravatar'       => __( 'Gravatar', 'zzz-translate' ),
    'GZip'           => __( 'GZip', 'zzz-translate' ),
    'HTML'           => __( 'HTML', 'zzz-translate' ),
    'html'           => __( 'html', 'zzz-translate' ),
    'https'          => __( 'https', 'zzz-translate' ),
    'id'             => __( 'id', 'zzz-translate' ),
    'ID'             => __( 'ID', 'zzz-translate' ),
    'IP'             => __( 'IP', 'zzz-translate' ),
    'MD5'            => __( 'MD5', 'zzz-translate' ),
    'MySQL'          => __( 'MySQL', 'zzz-translate' ),
    'nofollow'       => __( 'nofollow', 'zzz-translate' ),
    'oEmbed'         => __( 'oEmbed', 'zzz-translate' ),
    'pdf'            => __( 'pdf', 'zzz-translate' ),
    'PHP'            => __( 'PHP', 'zzz-translate' ),
    'PHPMailer'      => __( 'PHPMailer', 'zzz-translate' ),
    'reCAPTCHA'      => __( 'reCAPTCHA', 'zzz-translate' ),
    'REST API'       => __( 'REST API', 'zzz-translate' ),
    'Robots.txt'     => __( 'Robots.txt', 'zzz-translate' ),
    'robots.txt'     => __( 'robots.txt', 'zzz-translate' ),
    'RSS'            => __( 'RSS', 'zzz-translate' ),
    'Secure SSL'     => __( 'Secure SSL', 'zzz-translate' ),
    'Secure TLS'     => __( 'Secure TLS', 'zzz-translate' ),
    'SEO'            => __( 'SEO', 'zzz-translate' ),
    'seo'            => __( 'seo', 'zzz-translate' ),
    'SMTP'           => __( 'SMTP', 'zzz-translate' ),
    'SQL'            => __( 'SQL', 'zzz-translate' ),
    'SSL'            => __( 'SSL', 'zzz-translate' ),
    'TinyMCE'        => __( 'TinyMCE', 'zzz-translate' ),
    'TLS'            => __( 'TLS', 'zzz-translate' ),
    'URI'            => __( 'URI', 'zzz-translate' ),
    'URL'            => __( 'URL', 'zzz-translate' ),
    'User Agent'     => __( 'User Agent', 'zzz-translate' ),
    'WordPress cron' => __( 'WordPress cron', 'zzz-translate' ),
    'WP Mail'        => __( 'WP Mail', 'zzz-translate' ),
    'wp_mail'        => __( 'wp_mail', 'zzz-translate' ),
    'ZIP'            => __( 'ZIP', 'zzz-translate' ),
];
