<?php

// Штаты США

$data = [
    'AL' => __( 'Alabama', 'zzz-translate' ),
    'AK' => __( 'Alaska', 'zzz-translate' ),
    'AZ' => __( 'Arizona', 'zzz-translate' ),
    'AR' => __( 'Arkansas', 'zzz-translate' ),
    'CA' => __( 'California', 'zzz-translate' ),
    'CO' => __( 'Colorado', 'zzz-translate' ),
    'CT' => __( 'Connecticut', 'zzz-translate' ),
    'DE' => __( 'Delaware', 'zzz-translate' ),
    'DC' => __( 'District Of Columbia', 'zzz-translate' ),
    'FL' => __( 'Florida', 'zzz-translate' ),
    'GA' => __( 'Georgia', 'zzz-translate' ),
    'HI' => __( 'Hawaii', 'zzz-translate' ),
    'ID' => __( 'Idaho', 'zzz-translate' ),
    'IL' => __( 'Illinois', 'zzz-translate' ),
    'IN' => __( 'Indiana', 'zzz-translate' ),
    'IA' => __( 'Iowa', 'zzz-translate' ),
    'KS' => __( 'Kansas', 'zzz-translate' ),
    'KY' => __( 'Kentucky', 'zzz-translate' ),
    'LA' => __( 'Louisiana', 'zzz-translate' ),
    'ME' => __( 'Maine', 'zzz-translate' ),
    'MD' => __( 'Maryland', 'zzz-translate' ),
    'MA' => __( 'Massachusetts', 'zzz-translate' ),
    'MI' => __( 'Michigan', 'zzz-translate' ),
    'MN' => __( 'Minnesota', 'zzz-translate' ),
    'MS' => __( 'Mississippi', 'zzz-translate' ),
    'MO' => __( 'Missouri', 'zzz-translate' ),
    'MT' => __( 'Montana', 'zzz-translate' ),
    'NE' => __( 'Nebraska', 'zzz-translate' ),
    'NV' => __( 'Nevada', 'zzz-translate' ),
    'NH' => __( 'New Hampshire', 'zzz-translate' ),
    'NJ' => __( 'New Jersey', 'zzz-translate' ),
    'NM' => __( 'New Mexico', 'zzz-translate' ),
    'NY' => __( 'New York', 'zzz-translate' ),
    'NC' => __( 'North Carolina', 'zzz-translate' ),
    'ND' => __( 'North Dakota', 'zzz-translate' ),
    'OH' => __( 'Ohio', 'zzz-translate' ),
    'OK' => __( 'Oklahoma', 'zzz-translate' ),
    'OR' => __( 'Oregon', 'zzz-translate' ),
    'PA' => __( 'Pennsylvania', 'zzz-translate' ),
    'RI' => __( 'Rhode Island', 'zzz-translate' ),
    'SC' => __( 'South Carolina', 'zzz-translate' ),
    'SD' => __( 'South Dakota', 'zzz-translate' ),
    'TN' => __( 'Tennessee', 'zzz-translate' ),
    'TX' => __( 'Texas', 'zzz-translate' ),
    'UT' => __( 'Utah', 'zzz-translate' ),
    'VT' => __( 'Vermont', 'zzz-translate' ),
    'VA' => __( 'Virginia', 'zzz-translate' ),
    'WA' => __( 'Washington', 'zzz-translate' ),
    'WV' => __( 'West Virginia', 'zzz-translate' ),
    'WI' => __( 'Wisconsin', 'zzz-translate' ),
    'WY' => __( 'Wyoming', 'zzz-translate' ),
];
